/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {
      type: "doc",
      id: "README",
      label: "Home"
    },
    {
      type: "category",
      label: "Curso",
      items: [{ type: "autogenerated", dirName: "curso" }]
    },
    {
      type: "category",
      label: "Legislacao",
      items: [{ type: "autogenerated", dirName: "legislacao" }]
    },
    {
      type: "category",
      label: "FAQ",
      items: [{ type: "autogenerated", dirName: "faq" }]
    }
  ]
};

module.exports = sidebars;
